# Describe
This piece of code is used to have a quick look on the data.
Describe shows us, for each column, some basic info like the mean, the std, quartiles..
Before any analysis, knowing what data looks like is a great way to understand it and adapt formatting.

The code defines a script to describe a dataset, providing statistical summaries of its numerical columns. The main functionalities include:

1. **Command-Line Interface**:
   - The script uses `argparse` to handle command-line arguments, allowing users to specify the dataset file, and optional flags to drop empty columns (`-d` or `--drop`), print additional information (`-v` or `--verbose`), and include bonus information (`-b` or `--bonus`).

2. **Main Function (`describe`)**:
   - This function takes a DataFrame and optional flags as input and returns a DataFrame containing descriptive statistics of the numerical columns.
   - It can drop empty columns and include additional information like missing values and range if the `bonus` flag is set.

3. **Column Description (`describe_column`)**:
   - This helper function computes various statistics for a specific column, including count, mean, standard deviation, min, max, quantiles (25%, 50%, 75%), missing values, and range.

4. **Statistical Computations**:
   - Separate functions compute the mean (`compute_mean`), standard deviation (`compute_std`), min and max values (`find_min_max`), quantiles (`compute_quantile`), and total missing values (`get_total_missing_values`) for a column.

5. **Execution**:
   - The script reads a CSV file using a custom `open_csv` function from the `ft_dslr.tools` module.
   - It then describes the dataset based on the provided command-line arguments and prints the description.
   - If an error occurs during file opening or processing, it prints an error message.

The script is designed to be run from the command line, providing a flexible way to analyze and summarize datasets with optional verbosity and additional statistical information.

### Import libs and required functions

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from ft_dslr.tools import open_csv
from ft_dslr.describe import describe

In [3]:
pathTrain = '../data/external/datasets/dataset_train.csv'
pathTest = '../data/external/datasets/dataset_test.csv'

### Load data from csv
_With jupiter notebook, you can have a quick view of the loaded data frame by simply call the df variable._

In [4]:
dfTest = open_csv(pathTest)
dfTrain = open_csv(pathTrain)

In [5]:
dfTest

,Index,Hogwarts House,First Name,Last Name,Birthday,Best Hand,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,0,NaN,Rico,Sargent,2001-10-06,Right,41642.0,696.096071,3.020172,-6.960961,7.996,-365.151850,393.138185,4.207691,1046.742736,3.668983,0.373853,-244.48172,-13.62
1,1,NaN,Tamara,Shackelford,1998-01-08,Left,45352.0,-370.844655,2.965226,3.708447,6.349,522.580486,602.853051,6.460017,1048.053878,8.514622,0.577432,-231.29200,-26.26
2,2,NaN,Staci,Crandall,1998-09-15,Left,43502.0,320.303990,-6.185697,-3.203040,4.619,-630.073207,588.071795,-5.565818,936.437358,1.850829,-1.647150,-252.99343,200.15
3,3,NaN,Dee,Gavin,2001-05-10,Right,61831.0,407.202928,4.962442,NaN,NaN,-449.179806,427.699966,NaN,1043.397718,4.656573,1.164708,-244.01660,-11.15
4,4,NaN,Gregory,Gustafson,1999-02-01,Right,NaN,288.337747,3.737656,-2.883377,4.886,-449.732166,385.712782,2.876347,1051.377936,2.750586,0.102104,-243.99806,-7.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,NaN,Maria,Kidwell,1999-02-06,Left,45857.0,-554.181932,-5.647655,5.541819,-3.799,-591.764651,392.973420,7.048482,1047.648405,10.408749,1.882786,-248.39978,-94.89
396,396,NaN,Frederic,Koonce,1997-11-11,Left,51842.0,632.233530,6.754862,-6.322335,3.294,-221.848397,319.360250,3.921402,1035.681313,-0.169741,-1.074303,-246.87982,-15.53
397,397,NaN,Eugene,Peralta,1998-11-14,Right,61982.0,292.108738,5.234530,-2.921087,4.230,-787.036050,433.259967,3.898160,1069.794110,6.495579,-2.286537,-244.01333,1.25
398,398,NaN,Allan,Bentley,1998-10-13,Left,56020.0,-726.418553,6.735582,7.264186,3.908,511.960762,613.391514,7.244499,1042.058804,7.554259,-0.788817,-228.24290,-18.27
399,399,NaN,Clarence,Pope,1999-07-26,Left,46452.0,-735.939727,7.224872,NaN,2.889,NaN,513.457470,3.095942,1035.331589,0.477165,0.975627,-230.70067,-8.78

In [6]:
dfTrain

,Index,Hogwarts House,First Name,Last Name,Birthday,Best Hand,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,0,Ravenclaw,Tamara,Hsu,2000-03-30,Left,58384.0,-487.886086,5.727180,4.878861,4.722,272.035831,532.484226,5.231058,1039.788281,3.790369,0.715939,-232.79405,-26.89
1,1,Slytherin,Erich,Paredes,1999-10-14,Right,67239.0,-552.060507,-5.987446,5.520605,-5.612,-487.340557,367.760303,4.107170,1058.944592,7.248742,0.091674,-252.18425,-113.45
2,2,Ravenclaw,Stephany,Braun,1999-11-03,Left,23702.0,-366.076117,7.725017,3.660761,6.140,664.893521,602.585284,3.555579,1088.088348,8.728531,-0.515327,-227.34265,30.42
3,3,Gryffindor,Vesta,Mcmichael,2000-08-19,Left,32667.0,697.742809,-6.497214,-6.977428,4.026,-537.001128,523.982133,-4.809637,920.391449,0.821911,-0.014040,-256.84675,200.64
4,4,Gryffindor,Gaston,Gibbs,1998-09-27,Left,60158.0,436.775204,-7.820623,NaN,2.236,-444.262537,599.324514,-3.444377,937.434724,4.311066,-0.264070,-256.38730,157.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,1595,Gryffindor,Jung,Blank,2001-09-14,Right,49009.0,354.280086,-4.541837,-3.542801,5.702,-497.235066,618.220213,-5.231721,964.219853,3.389086,-0.649983,-250.39401,185.83
1596,1596,Slytherin,Shelli,Lock,1998-03-12,Left,63296.0,367.531174,6.061064,-3.675312,1.757,-643.271092,445.827565,2.238112,1056.147366,5.825263,-0.333962,-246.42719,44.80
1597,1597,Gryffindor,Benjamin,Christensen,1999-10-24,Right,63905.0,544.018925,-3.203269,-5.440189,6.065,-385.150457,635.211486,-5.984257,953.866685,1.709808,0.071569,-251.63679,198.47
1598,1598,Hufflepuff,Charlotte,Dillon,2001-09-21,Left,82713.0,453.676219,3.442831,-4.536762,6.738,-831.741123,383.444937,3.813111,1087.949205,3.904100,-0.531875,-246.19072,-76.81
1599,1599,Hufflepuff,Kylie,Nowak,2000-08-21,Left,48639.0,688.911989,5.421046,-6.889120,6.593,-234.207911,339.775154,7.208415,1034.928004,2.052215,0.150532,-244.02063,-54.77

### take a look on the describe result

In [7]:
describe(dfTrain)

,Info,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,Count,1566.000000,1568.000000,1567.000000,1569.000000,1561.00000,1565.000000,1565.000000,1557.000000,1566.000000,1570.000000,1560.000000,1600.000000,1600.000000
1,Mean,49634.570243,39.797131,1.141020,-0.387863,3.15391,-224.589915,495.747970,2.963095,1030.096946,5.950373,-0.053427,-243.374409,21.958013
2,Std,16674.479577,520.132330,5.218016,5.211132,4.15397,486.189433,106.251202,4.424353,44.111025,3.146852,0.971146,8.780895,97.601087
3,Min,-24370.000000,-966.740546,-10.295663,-10.162119,-8.72700,-1086.496835,283.869609,-8.858993,906.627320,-4.697484,-3.313676,-261.048920,-181.470000
4,25%,38516.000000,-489.493777,-4.304245,-5.259095,3.09900,-577.580096,397.511047,2.218653,1026.324832,3.652442,-0.670996,-250.647270,-41.840000
5,50%,49018.000000,261.644731,3.486307,-2.572919,4.62500,-418.660994,464.327598,4.379618,1045.533335,5.877582,-0.043296,-244.867510,-2.510000
6,75%,60918.000000,525.909540,5.421046,4.906820,5.66800,258.777525,597.703964,5.836217,1058.485415,8.254311,0.594446,-232.536750,50.890000
7,Max,104956.000000,1016.211940,11.612895,9.667405,10.03200,1092.388611,745.396220,11.889713,1098.958201,13.536762,3.056546,-225.428140,279.070000

In [8]:
describe(dfTest, drop=True)

,Info,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,Count,387.000000,387.000000,389.000000,392.000000,394.000000,390.000000,392.000000,389.000000,389.000000,390.000000,392.000000,400.000000,400.000000
1,Mean,50088.971576,48.155326,1.385517,-0.537843,3.411071,-220.169594,495.937543,2.829816,1030.885777,5.776860,0.022985,-243.181109,23.367450
2,Std,15452.744803,511.875159,5.048793,5.112229,3.886250,497.030335,101.527670,4.311657,45.288575,3.213497,1.017705,8.716274,95.066887
3,Min,4536.000000,-802.725180,-9.687662,-8.700635,-8.183000,-1041.323658,319.360250,-7.189090,906.932050,-1.162060,-2.871119,-259.866780,-143.520000
4,25%,40193.000000,-482.139096,-4.183731,-5.205897,3.534000,-577.790039,400.888868,2.227669,1028.499974,3.243049,-0.645976,-250.143180,-38.440000
5,50%,49297.000000,297.347711,3.635899,-2.910220,4.717000,-407.494571,486.508729,4.297151,1047.660109,5.733112,0.063305,-244.745460,-2.260000
6,75%,60182.000000,511.393084,5.414913,4.785424,5.580000,249.792741,591.524186,5.674959,1060.383740,8.141893,0.720617,-232.774610,45.850000
7,Max,99744.000000,870.063498,9.678462,8.027252,8.604000,939.317135,667.674165,10.366995,1099.966073,13.390013,3.205525,-226.003820,282.430000

# _Bonus_

This part of the subject comes with a bonus.

We have chosen to add the number of missing values and the range, which are key indicators of the comprehensibility of the data.

In [11]:
describe(dfTrain, drop=True, bonus=True)

,Info,Arithmancy,Astronomy,Herbology,Defense Against the Dark Arts,Divination,Muggle Studies,Ancient Runes,History of Magic,Transfiguration,Potions,Care of Magical Creatures,Charms,Flying
0,Count,1566.000000,1568.000000,1567.000000,1569.000000,1561.00000,1565.000000,1565.000000,1557.000000,1566.000000,1570.000000,1560.000000,1600.000000,1600.000000
1,Mean,49634.570243,39.797131,1.141020,-0.387863,3.15391,-224.589915,495.747970,2.963095,1030.096946,5.950373,-0.053427,-243.374409,21.958013
2,Std,16674.479577,520.132330,5.218016,5.211132,4.15397,486.189433,106.251202,4.424353,44.111025,3.146852,0.971146,8.780895,97.601087
3,Min,-24370.000000,-966.740546,-10.295663,-10.162119,-8.72700,-1086.496835,283.869609,-8.858993,906.627320,-4.697484,-3.313676,-261.048920,-181.470000
4,25%,38516.000000,-489.493777,-4.304245,-5.259095,3.09900,-577.580096,397.511047,2.218653,1026.324832,3.652442,-0.670996,-250.647270,-41.840000
5,50%,49018.000000,261.644731,3.486307,-2.572919,4.62500,-418.660994,464.327598,4.379618,1045.533335,5.877582,-0.043296,-244.867510,-2.510000
6,75%,60918.000000,525.909540,5.421046,4.906820,5.66800,258.777525,597.703964,5.836217,1058.485415,8.254311,0.594446,-232.536750,50.890000
7,Max,104956.000000,1016.211940,11.612895,9.667405,10.03200,1092.388611,745.396220,11.889713,1098.958201,13.536762,3.056546,-225.428140,279.070000
8,Missing values,34.000000,32.000000,33.000000,31.000000,39.00000,35.000000,35.000000,43.000000,34.000000,30.000000,40.000000,0.000000,0.000000
9,range,129326.000000,1982.952486,21.908558,19.829525,18.75900,2178.885445,461.526611,20.748706,192.330881,18.234246,6.370222,35.620780,460.540000